// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-oZiIXDo1WNtWlRPuRoYWjABYBWV1E6Y',
    appId: '1:86073255564:web:bebc4fb00deed910793da9',
    messagingSenderId: '86073255564',
    projectId: 'hopeapp-b5634',
    authDomain: 'hopeapp-b5634.firebaseapp.com',
    storageBucket: 'hopeapp-b5634.appspot.com',
    measurementId: 'G-9ZKFXHMG74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrDFoLFHRS1DTsLaBU4O6C9INZs0btuI',
    appId: '1:86073255564:android:db9a54fe22ba8fe5793da9',
    messagingSenderId: '86073255564',
    projectId: 'hopeapp-b5634',
    storageBucket: 'hopeapp-b5634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADilU_3Be2I8HyTgVDuyxsdX959BFAb6A',
    appId: '1:86073255564:ios:e00602e902d57a51793da9',
    messagingSenderId: '86073255564',
    projectId: 'hopeapp-b5634',
    storageBucket: 'hopeapp-b5634.appspot.com',
    iosClientId: '86073255564-qms9kduf3g0a2g9o7pk5nlask8bofflb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopeApp',
  );
}
